[package]
name = "persistence"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
botcore = { path = "../botcore" }
rust_decimal.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
turso = { version = "0.7.2", features = ["sync"] }

[dev-dependencies]
rust_decimal_macros.workspace = true
tempfile = "3"
